feature: 717 performance section
EyeSeeTea/zebra-dev pull request #21
Opened 2024-09-16 13:54 UTC by delemaf

### :pushpin: References

-   **Issue:** Closes #?

### :memo: Implementation

### :video_camera: Screenshots/Screen capture

### :fire: Notes to the tester

2024-10-03 06:07 UTC, anagperal commented on src/data/repositories/PerformanceOverviewD2Repository.ts
> +                    `dx:${INDICATORS_717_PERFORMANCE.map(({ id }) => id).join(";")}`,
In the future we can get these Program Indicators from DataStore like Maps.

2024-10-03 06:08 UTC, anagperal commented on src/data/repositories/PerformanceOverviewD2Repository.ts
> +                    "pe:THIS_YEAR",
Period dimension has to be this year?

2024-10-03 06:09 UTC, anagperal commented on src/webapp/pages/dashboard/use717Performance.ts
> +            let color: "green" | "red" | "grey" | "normal" | undefined;
Maybe better to create a function to get the color

2024-10-03 06:09 UTC, anagperal requested changes
Thanks @9sneha-n ! Just a couple of comments (or now that Florian is not here should I chage it?)

2024-10-03 10:14 UTC, 9sneha-n commented on src/data/repositories/PerformanceOverviewD2Repository.ts
> +                    "pe:THIS_YEAR",
checked with team.

2024-10-11 10:45 UTC, anagperal approved these changes
thanks @9sneha-n !!

2024-10-15 09:16 UTC, merged