fix: show only items with "ALL" incident status
EyeSeeTea/zebra-dev pull request #43
Opened 2024-12-11 20:46 UTC by deeonwuli

### :pushpin: References

-   **Issue:** Closes #?

### :memo: Implementation
- [x] Fix total cards count: when no filter is selected, only alerts with "ALL" event status are shown

### :video_camera: Screenshots/Screen capture

https://github.com/user-attachments/assets/a72a6754-d822-4849-ad33-8971c563723a

### :fire: Notes to the tester

2024-12-12 11:24 UTC, anagperal commented on src/data/repositories/PerformanceOverviewD2Repository.ts
> +                return matchesDisease && matchesHazard && matchesIncidentStatus;
great, it's much easier to understand!

2024-12-12 11:25 UTC, anagperal approved these changes
> thanks @deeonwuli !!

tested and when applying Hazard type filter is not working correct: 

![Screenshot from 2024-12-12 12-32-52](https://github.com/user-attachments/assets/732f2f8a-356a-413f-87af-b1524f758f6b)

2024-12-12 11:34 UTC, anagperal requested changes
@deeonwuli check when we apply more filters (check comments in code): 

![Screenshot from 2024-12-12 12-32-52](https://github.com/user-attachments/assets/8282b93d-0135-4657-9be3-d1eaee4ec4ba)

2024-12-12 11:36 UTC, anagperal commented
@bhavananarayanan I have found that some program indicators may not be properly configured. It seems to happen with program indicator used in card for hazard type, for example [# of active verified - Environmental type](https://metadata.eyeseetea.com/rsl-zebra240/dhis-web-maintenance/index.html#/edit/indicatorSection/programIndicator/Xec7fRcZ1wy) has this filter: `Event Type=="RTSL_ZEB_OS_HAZARD_TYPE_ENVIRONMENTAL" && Enrollment status=="ACTIVE"` in for progam indicators for the different Incident Status ([# of active verified - Environmental type - Alert](https://metadata.eyeseetea.com/rsl-zebra240/dhis-web-maintenance/index.html#/edit/indicatorSection/programIndicator/z3EbI98pgjG)) the filter  is `National Incident Status=="PHEOC_STATUS_ALERT" && Verification Status=="RTSL_ZEB_AL_OS_VERIFICATION_VERIFIED" && Event Type=="RTSL_ZEB_OS_HAZARD_TYPE_ENVIRONMENTAL" && Enrollment status=="ACTIVE"`, so the one without the incident status is not filtering by Verification Status=="RTSL_ZEB_AL_OS_VERIFICATION_VERIFIED" and that is because when there is no incident status filter we have 3 events but when we apply the filter we cannot see any Environmental card:
![Screenshot from 2024-12-12 12-35-38](https://github.com/user-attachments/assets/3ec833d0-ffcf-432b-a663-385027d0c67f)

![Screenshot from 2024-12-12 12-35-52](https://github.com/user-attachments/assets/fe07d550-947b-4ec8-9c7d-0242aa5da6e8)
![Screenshot from 2024-12-12 12-35-47](https://github.com/user-attachments/assets/310e4ebe-53ca-44a7-846f-a00a0badfb4a)
![Screenshot from 2024-12-12 12-35-42](https://github.com/user-attachments/assets/77eff8ae-2161-46f6-89ed-602e6d748308)


![Screenshot from 2024-12-12 12-36-40](https://github.com/user-attachments/assets/214ac07d-1905-43ae-9d5e-cf8dd04ba631)

2024-12-12 11:40 UTC, anagperal commented on src/data/repositories/PerformanceOverviewD2Repository.ts
> +                const matchesHazard = !filters.hazard || item.type === "hazard";
you miss here `item.name === filters.hazard` like in the disease match

2024-12-12 12:18 UTC, anagperal approved these changes
thanks @deeonwuli !!

2024-12-16 06:42 UTC, bhavananarayanan commented
> @bhavananarayanan I have found that some program indicators may not be properly configured. It seems to happen with program indicator used in card for hazard type, for example [# of active verified - Environmental type](https://metadata.eyeseetea.com/rsl-zebra240/dhis-web-maintenance/index.html#/edit/indicatorSection/programIndicator/Xec7fRcZ1wy) has this filter: `Event Type=="RTSL_ZEB_OS_HAZARD_TYPE_ENVIRONMENTAL" && Enrollment status=="ACTIVE"` but in progam indicators for the different Incident Status ([# of active verified - Environmental type - Alert](https://metadata.eyeseetea.com/rsl-zebra240/dhis-web-maintenance/index.html#/edit/indicatorSection/programIndicator/z3EbI98pgjG)) the filter is `National Incident Status=="PHEOC_STATUS_ALERT" && Verification Status=="RTSL_ZEB_AL_OS_VERIFICATION_VERIFIED" && Event Type=="RTSL_ZEB_OS_HAZARD_TYPE_ENVIRONMENTAL" && Enrollment status=="ACTIVE"`, so the one without the incident status is not filtering by `Verification Status=="RTSL_ZEB_AL_OS_VERIFICATION_VERIFIED"` and that is why when there is no incident status filter we have 3 events but when we apply the filter we cannot see any Environmental card: ![Screenshot from 2024-12-12 12-35-38](https://private-user-images.githubusercontent.com/49402898/395140139-3ec833d0-ffcf-432b-a663-385027d0c67f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzE1ODEsIm5iZiI6MTczNDMzMTI4MSwicGF0aCI6Ii80OTQwMjg5OC8zOTUxNDAxMzktM2VjODMzZDAtZmZjZi00MzJiLWE2NjMtMzg1MDI3ZDBjNjdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA2NDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MWY1MjViNjc4YThjNTg2YTcwNDNlZGI0MjJlMWEwOTQ5NTkxNGZmZDhkMzBkNTUzNjFlZDg1YmY4NzljYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rrq5aOBMCHNhv3f_b0K1PWrC4JykY6VeaCI1t4thINE)
> 
> ![Screenshot from 2024-12-12 12-35-52](https://private-user-images.githubusercontent.com/49402898/395140169-fe07d550-947b-4ec8-9c7d-0242aa5da6e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzE1ODEsIm5iZiI6MTczNDMzMTI4MSwicGF0aCI6Ii80OTQwMjg5OC8zOTUxNDAxNjktZmUwN2Q1NTAtOTQ3Yi00ZWM4LTljN2QtMDI0MmFhNWRhNmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA2NDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NzhhMmY4ZTMwOTdmMWQ0MzVhMWY1MzM5ZWYzNjA4ZGQ3N2I0ZjFjN2FiNWEyNGJhNjk3NTAyODJiNjc2ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jjEvPL8FOPipMDU96DXzzcf_5-aB1VONwuPcL2meSvg) ![Screenshot from 2024-12-12 12-35-47](https://private-user-images.githubusercontent.com/49402898/395140173-310e4ebe-53ca-44a7-846f-a00a0badfb4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzE1ODEsIm5iZiI6MTczNDMzMTI4MSwicGF0aCI6Ii80OTQwMjg5OC8zOTUxNDAxNzMtMzEwZTRlYmUtNTNjYS00NGE3LTg0NmYtYTAwYTBiYWRmYjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA2NDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZGMyNmIxMWNmZmZhZmQ3OWU1ZGEzNGEwZGQ4ODZlZTE5YTU2NGJlMzlmYmRkNmE3MDQ1ODE0NTQ2MGRlNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vQbKQU7vJ3HHxBAL4mxafrsGmPrMl89n9vBWFDcKdbY) ![Screenshot from 2024-12-12 12-35-42](https://private-user-images.githubusercontent.com/49402898/395140176-77eff8ae-2161-46f6-89ed-602e6d748308.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzE1ODEsIm5iZiI6MTczNDMzMTI4MSwicGF0aCI6Ii80OTQwMjg5OC8zOTUxNDAxNzYtNzdlZmY4YWUtMjE2MS00NmY2LTg5ZWQtNjAyZTZkNzQ4MzA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA2NDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzZWUxNTAzOTQ3ZDI0OWNjNjczYjZlZGQwMGE5ODVlZjlhYTEyM2JkYmY4M2I4OGIzMjcyOWIxN2Q4Y2EyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CrhFIWOxYuoMr1RzZppeVIS4mqyHfjBYrrqlq_WUdhg)
> 
> ![Screenshot from 2024-12-12 12-36-40](https://private-user-images.githubusercontent.com/49402898/395140419-214ac07d-1905-43ae-9d5e-cf8dd04ba631.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzE1ODEsIm5iZiI6MTczNDMzMTI4MSwicGF0aCI6Ii80OTQwMjg5OC8zOTUxNDA0MTktMjE0YWMwN2QtMTkwNS00M2FlLTlkNWUtY2Y4ZGQwNGJhNjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA2NDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllMDI2NWZhYjk1ZWE3OGEyYmYxMDdiM2IwYTE5MWY3M2MyNzc4OWU2YjE3NDA3NDYwZjFiY2FmNzhmYjM4MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.d-pd8HrNWdPmd0G8-HnCmAbSPcFPXZEPmyfb-qIqD3U)

Thanks, I have corrected the program indicator for # active verified - Environment type to include the filter for Verified status in Dev 40 and Prod.

2024-12-16 06:58 UTC, merged